name: Build and Deploy to Firebase

on:
  repository_dispatch:
    types: [deploy-event]  # This is a custom event type that you will use to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Set this to the Node.js version you are using
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build Next.js App
        run: npm run build
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Deploy
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
